---
### Clone gh-cli repo ###

- name: Create gh-cli repo dir
  file:
    path: /home/gh-cli
    state: directory

- name: Clone gh-cli
  shell: cd /home && git clone https://github.com/cli/cli.git gh-cli


### Install gh-api ###

- name: Create gh-cli tool folder
  file:
    path: /opt/tools/gh-cli
    state: directory

- make:
    chdir: /home/gh-cli
    target: install
    params:
      prefix: /opt/tools/gh-cli

- name: check gh-cli
  shell: ls /opt/tools/gh-cli

...