---
### Install Homebrew packages ###

- name: Install Development Tools groupinstall
  shell: 'yum -y groupinstall "Development Tools"'

- name: Install packages
  yum:
    pkg: ['file']
    state: latest

### Install gh-api ###

- name: Install gh-api
  shell: brew install gh

...