---
### Install RPM packages ###

- name: Install RCMTOOLS repository
  yum:
    name: http://download.devel.redhat.com/rel-eng/RCMTOOLS/latest-redhat-rcminternal-release-server-rhel-7.noarch.rpm
    state: present

- name: Import RCMTOOLS repository key
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-rcminternal


- name: Install packages
  yum:
    pkg: ['brewkoji']
    state: latest

### Download PME ###

- name: Create tools directory for pme
  file:
    path: /opt/tools/pme
    state: directory
    recurse: yes
    owner: root
    group: root

- name: Dowload PME extension
  get_url:
    url: http://central.maven.org/maven2/org/commonjava/maven/ext/pom-manipulation-ext/{{pme_version}}/pom-manipulation-ext-{{pme_version}}.jar
    dest: /opt/tools/pme
    owner: root
    group: root

### Configure Maven ###

- name: Add PME extension to Maven
  file:
    src: /opt/tools/pme/pom-manipulation-ext-{{pme_version}}.jar
    dest: /opt/tools/apache-maven-{{ item }}/lib/ext/pom-manipulation-ext-{{pme_version}}.jar
    state: link
    mode: 0644
  with_items:
  - "{{ maven_versions }}"

- name: Create qa tools directory
  file:
    path: /qa/tools/opt
    state: directory
    recurse: yes
    owner: root
    group: root

- name: Create qa tools Maven symlinks
  file:
    src: /opt/tools/apache-maven-{{ item }}
    dest: /qa/tools/opt/maven-{{ item }}-prod
    state: link
    mode: 0644
  with_items:
  - "{{ maven_versions }}"

### Prepare Maven repositories ###

- name: Create 70 repository
  file:
    path: /m2/70
    state: directory
    recurse: yes
    owner: jenkins
    group: jenkins

### Download and Generate PiG/PFG ###

- name: Install PNC CLI
  pip:
    name: pnc_cli
    extra_args: --user 
  become: yes
  become_user: jenkins

- name: Create tools directory for PiG
  file:
    path: /opt/tools/pig/product-files-generator
    state: directory
    recurse: yes
    owner: root
    group: root

- name: Git SSL verify to False
  command: "git config --global http.sslVerify false"

- name: Clone Product Files Generator
  command: "git clone https://gitlab.cee.redhat.com/middleware/product-files-generator.git /opt/tools/pig/product-files-generator"

- name: Package Product Files Generator
  command: "/qa/tools/opt/maven-3.6.0-prod/bin/mvn -f /opt/tools/pig/product-files-generator/pom.xml clean install -DskipTests=true -Dmaven.repo.local=/m2/70"
  environment:
    JAVA_HOME: /opt/tools/jdk1.8

- name: Create Product Files Generator JAR symlinks
  file:
    src: /opt/tools/pig/product-files-generator/core/target/product-files-generator.jar
    dest: /opt/tools/pig/product-files-generator.jar
    state: link
    mode: 0644
...